kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  set-real-ip-from: "0.0.0.0/0"
  real_ip_header:    "X-Forwarded-For"
  real_ip_recursive: "on"
  server-tokens: "false"
  proxy-body-size: "200m"
  client-body-timeout: "300"
  # keepalive_timeout is 75s by default, if service uses websocket the value should be larger than 3600s
  keepalive_timeout: "3600"
  proxy-connect-timeout: "60"
  proxy-read-timeout: "300"
  proxy-send-timeout: "300"
  use-proxy-protocol: "true"
