kind: Pod
apiVersion: v1
metadata:
  name: default-service
  labels:
    app: default-service
spec:
  containers:
    - name: default-service
      image: hashicorp/http-echo
      args:
        - "-text=Welcome here !!! "
---
kind: Service
apiVersion: v1
metadata:
  name: default-service
spec:
  selector:
    app: default-service
  ports:
    - port: 5678 # Default port for image
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: default-service
   annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - default.letrungka.info
    secretName: letrungka.info-secret  
  rules:
  - host: default.letrungka.info
    http:
      paths:
        - path: /
          backend:
            serviceName: default-service
            servicePort: 5678

