apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-testing-with-ssl
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
  - hosts:
    - test.letrungka.info
    secretName: letrungka.info-secret
  rules:
  - host: test.letrungka.info
    http:
      paths:
        - path: /
          backend:
            serviceName: sun-asterisk-service
            servicePort: 5678
